version: '3.8'

services:
  app:
    build:
      context: .
      args:
        COMMIT_HASH: ${COMMIT_HASH:-unknown}
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - OTEL_EXPORTER_OTLP_ENDPOINT=clickstack:4318
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  clickstack:
    image: docker.hyperdx.io/hyperdx/hyperdx-local
    ports:
      - 8000:8000 # API
      - 8081:8081 # APP
      - 4317:4317 # OTLP gRPC
      - 4318:4318 # OTLP HTTP
    environment:
      - HYPERDX_APP_PORT=8081
    volumes:
      - ./volumes/db:/data/db
      - ./volumes/ch_data:/var/lib/clickhouse
      - ./volumes/ch_logs:/var/log/clickhouse-server