# Minimal Vector configuration for structured log collection

[sources.app_logs]
type = "docker_logs"
include_labels = ["com.docker.compose.service=app"]

[transforms.parse_logs]
type = "remap"
inputs = ["app_logs"]
source = '''
# Parse JSON logs from the Go app
if exists(.message) {
  parsed, err = parse_json(.message)
  if err == null {
    .level = parsed.level
    .msg = parsed.msg
    .method = parsed.method
    .path = parsed.path
    .duration = parsed.duration
  }
}
'''

[sinks.console]
type = "console"
inputs = ["parse_logs"]
encoding.codec = "text"
encoding.template = "{{ timestamp }} [{{ level }}] {{ msg }}"